server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: COMPANY-SERVICE
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company/**

        - id: STOCK-SERVICE
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stock/**



eureka:
  client:
    resgister-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost